targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/api.graphql.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/queries/**.graphql
