name: graphql_jobs
description: GraphQL Jobs Flutter application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  graphql_flutter: ^5.0.1
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  shimmer: ^2.0.0
  timeago: ^3.2.2
  url_launcher: ^6.0.17

dev_dependencies:
  artemis: '>=7.0.0 <8.0.0'
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1
  json_serializable: ^6.1.1
  lint: ^1.7.2

flutter:
  uses-material-design: true
  generate: true
